#!/run/current-system/sw/bin/bash
GUEST_NAME="$1"
HOOK_NAME="$2"
STATE_NAME="$3"
MISC="${@:4}"

set -e  # Exit if any command fails

# Special case for win11
if [ "$GUEST_NAME" = "win11" ]; then
    if [ "$HOOK_NAME" = "prepare" ] && [ "$STATE_NAME" = "begin" ]; then
        nvidia-bind-vfio
    elif [ "$HOOK_NAME" = "release" ] && [ "$STATE_NAME" = "end" ]; then
        nvidia-unbind-vfio
    fi
fi